package com.example.demo;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.google.gson.Gson;

@DynamoDBTable(tableName = "MediaNotification")
public class MediaNotification
{
    private String id;
    private String notification;

    public MediaNotification(String id, String notification)
    {
        this.id = id;
        this.notification = notification;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId()
    {
        return id;
    }

    public void setId(String id)
    {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getNotification()
    {
        return notification;
    }

    public void setNotification(String notification)
    {
        this.notification = notification;
    }


    public static MediaNotification from(String string)
    {
        Gson gson = new Gson();
        return gson.fromJson(string, MediaNotification.class);
    }

}
